### PR TITLE
MMA Foil Rarity Correction

### PR DESCRIPTION
**Pull request by tritoch**
Looks like the rarities were a bit off.  Previously was giving 1/10 odds of mythic, 2/10 rare, 3/10 uncommon.  Actual occurances for a case (4 boxes) are approximately 12(mythic)/84(rare)/288(uncommon).  Adjusted the random values to align with this.

It looks like VMA references the selectRarity function and needs adjusted but I'm not sure how all that works.

### CODE REVIEW

**Comment by aeosynth** [comment]
Do you have a source for those numbers?

**Comment by aeosynth** [comment]
Leave a comment detailing the numbers.

**Comment by tritoch** [comment]
I found this: http://www.mtgsalvation.com/forums/magic-fundamentals/magic-general/604687-all-foils-printed-equally-in-modern-masters-2015?comment=6
It's obviously not authoritative but seems more reasonable than the current numbers.

**Comment by tritoch** [comment]
This post has the same ratio: http://www.mtgsalvation.com/forums/market-street/market-street-cafe/496025-modern-masters-foil-distribution?comment=7 (17 foil commons, 5 foil uncommons, 1.5 foil rares and 0.21 mythics = 1 : 7.14 : 23.80 : 83.95)

**Comment by aeosynth** [comment]
fixed with ff97d89162e59778fc7f82aafac0a179ec2c8777

work with packs instead of cases

**Pull request closed without merging**
