### PR TITLE
Help command

### PR DESCRIPTION
**Pull request by sirugh**
Saw some dude griping about the name command not being intuitive. Didn't know what direction you wanted to end up with that, but at least a `/help` command will benefit the ux :)

### CODE REVIEW

**Comment by aeosynth** [comment]
what if the placeholder was `/nick name`

**Comment by sirugh** [comment]
That may not always be the only command users can issue in the chat.

**Comment by aeosynth** [comment]
i still feel like a `/nick name` placeholder is fine. `/help` can be added if we ever get more commands

**Comment by sirugh** [comment]
Fair enough.

**Pull request closed without merging**
